extensions:
  health_check:
  pprof:
  zpages:

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: ${ATMO_TRACER_HONEYCOMB_API_ENDPOINT}
    headers:
      "x-honeycomb-team":  ${ATMO_TRACER_HONEYCOMB_API_KEY}
      "x-honeycomb-dataset": ${ATMO_TRACER_HONEYCOMB_DATASET}
  file:
    path: ./traces/traces.json

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, file]
