FROM golangci/golangci-lint:1.45.2

RUN curl -L -o install.sh https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
RUN cat install.sh
RUN export PATH="$(go env GOPATH)/bin:$PATH"
RUN echo $PATH
RUN ["sh",  "install.sh", "-b",  "$(go env GOPATH)/bin",  "v1.45.2"]
RUN which golangci-lint

RUN golangci-lint --version

RUN mkdir -p /tmp/linttime
WORKDIR /tmp/linttime

CMD ["golangci-lint", "run",  "./..."]
