FROM golang:1.18

RUN apt-get update && apt-get install -y xz-utils
RUN go install github.com/itchyny/gojq/cmd/gojq@latest

RUN mkdir -p /tmp/wasmtime
COPY docker-deps.sh /tmp/wasmtime/
WORKDIR /tmp/wasmtime

RUN ./docker-deps.sh
