name: ci

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          cache: true
      - run: go mod download

      - name: Build sat
        run: |
          make sat

      - name: Run stdin test
        run: |
          echo "world" | .bin/sat --stdin ./examples/hello-echo/hello-echo.wasm

      - name: Run Go tests
        run: |
          go test -v ./...

  image:
    needs: [test, lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Build sat image
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          tags: suborbital/sat:dev

      - name: Test sat container
        run: |
          docker run -id -e SAT_HTTP_PORT=8080 -p 8080:8080 -v $(pwd)/examples:/examples suborbital/sat:dev sat /examples/hello-echo/hello-echo.wasm
          sleep 1
          curl -s localhost:8080 -d 'world'

      - if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/metadata-action@v4
        id: docker_meta
        with:
          images: suborbital/sat,ghcr.io/suborbital/sat
          tags: |
            type=match,pattern=(v.*)
          flavor: |
            latest=auto

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Build and push sat image
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  bin:
    needs: [test, lint]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goreleaser/goreleaser-cross:v1.20.0

    steps:
      - uses: actions/checkout@v3
      # temporary work around
      - run: git config --system --add safe.directory /__w/sat/sat

      - uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          install-only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: startsWith(github.ref, 'refs/tags/v')
        run: goreleaser release --clean

      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: goreleaser release --clean --snapshot
