name: Testapalooza

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache Go mods
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go mod download

      - name: Run stdin test
        run: |
          make sat
          make constd
          echo "world" | .bin/sat --stdin ./examples/hello-echo/hello-echo.wasm

      - name: Run Go tests
        run: |
          go test -v ./...
